default:	
	gcc -o myripsniffer myripsniffer.c -lpcap
	gcc -o myripresponse myripresponse.c -lpcap

myripsniffer:
	gcc -o myripsniffer myripsniffer.c -lpcap

myripresponse:
	gcc -o myripresponse myripresponse.c -lpcap

clean:
	rm -f *.o myripsniffer myripresponse

